project:
  type: website
  resources:
    - CNAME
    - files/*

website:
  title: "Eric Wiemer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: false



