project:
  type: website
  resources:
    - CNAME
    - files/*
    - images/*

website:
  title: "Eric Wiemer, PhD"
  navbar:
    right: 
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - icon: envelope-fill
        href: mailto:ewiemer30@gmail.com
        aria-label: Email
      - icon: bluesky
        href: https://bsky.app/profile/ericwiemer.com
        aria-label: Bluesky
      

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: false



